# dbt Profiles Configuration
# This file should be in ~/.dbt/profiles.yml or project-specific location
# DO NOT commit actual credentials to version control

iot_data_pipeline:
  target: dev
  outputs:
    dev:
      type: postgres
      host: localhost
      user: postgres
      password: postgres
      port: 5432
      dbname: iot_analytics
      schema: analytics
      threads: 4
      keepalive_idle: 0

    prod:
      type: postgres
      host: "{{ env_var('POSTGRES_HOST') }}"
      user: "{{ env_var('POSTGRES_USER') }}"
      password: "{{ env_var('POSTGRES_PASSWORD') }}"
      port: "{{ env_var('POSTGRES_PORT') | as_number }}"
      dbname: "{{ env_var('POSTGRES_DATABASE') }}"
      schema: analytics
      threads: 8

